### ISSUE TITLE
CIDR lookups

### ISSUE THREAD

**Issue by p0pr0ck5** [p0pr0ck5/FreeWAF#106]

**Comment by p0pr0ck5** [comment]
Done in 4d911b710ea9057295a849a6615d1000343b4815

**Comment by shel3over** [comment]
What about ipv6 ?

**Comment by p0pr0ck5** [comment]
@shel3over ipv6 isn't currently supported in the upstream lib we use (`hamishforbes/lua-resty-iputils`) doesn't provide ipv6 support. Patches to either upstream or our local inclusion are welcome :)
