### ISSUE TITLE
parse_request_body doesn't support application/x-www-form-urlencoded; charset=utf-8

### ISSUE THREAD

**Issue by r--w** [p0pr0ck5/FreeWAF#114]
Some clients send content-type header with additional charset encoding for example:
`application/x-www-form-urlencoded; charset=utf-8`
So direct comparison in https://github.com/p0pr0ck5/FreeWAF/blob/f4036303aede9517eb13d6bfbb5bee2a50284568/lib/request.lua#L86 doesn't work.

**Comment by p0pr0ck5** [comment]
Hello!

Yes, this issue was addressed in issue #102 and has been fixed in the development branch (see 33fc8d17e36c46a45e5c09e4e8dd136a408405d0). Are there further improvements you would like to see in this area?

**Comment by r--w** [comment]
Thank you.
