### ISSUE TITLE
a urgent enhancement

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#115]
when you update some rules, you should reload nginx which is not suitable for production environment.

**Comment by p0pr0ck5** [comment]
In what environment is it not suitable to _reload_ nginx? Reloading is a graceful procedure. Any sort of configuration change generally requires a reload. Not doing so means re-reading the config with every execution, which is terribly inefficient.

**Comment by hy05190134** [comment]
@p0pr0ck5  why not reload nginx when it is used in a lot of machines in the CDN system, we can just put rules in the redis and autoload rules without reloading nginx

**Comment by mickygough** [comment]
If you have a lot of machines in the CDN system you're going to be managing them with a configuration management system of some kind - Puppet/Chef/Ansible, etc. Adding a rule to reload nginx on all systems when the rules change is not a hard thing. If you have a lot of machines and you're not using configuration management you should think about it.

**Comment by hy05190134** [comment]
@mickygough  thanks for your suggestion, we just already have ansible to manager configuration, but we just not want to reload nginx every time when just modify rule, that's why we use autoload mechanism to apply and we store execrable rule into redis.

**Comment by p0pr0ck5** [comment]
There may be some merrit to supporting a memory DB like redis for rules, but that smacks of organization-specific requirements. It may be useful to some people, but might force others to use too-specific an architecture. If someone wants to work on adding support for this, patches welcome :)

**Comment by mickygough** [comment]
It'd require an external script capable of reading rulesets, generating offseets, and inserting them into Redis. It'd somehow need to do this in such a way that it prevented unpredictable behaviour if a request was currently reading in the ruleset from redis.
Not arguing against the change, it seems like it could be useful. Just thinking about how it would need to be implemented.

**Comment by p0pr0ck5** [comment]
For posterity, I'm marking this as wontfix.
