### ISSUE TITLE
support for pmFromFile in modsec2freewaf.pl

### ISSUE THREAD

**Issue by rm3nchaca** [p0pr0ck5/FreeWAF#119]
Hi!
pmFromFile is not supported.
With this lines, it can be posible to load a file and generate a string with "attacker1|attacker2|...." and use the existing pattern match operator.

my $valid_operators = {
	contains 	=> 'CONTAINS',
	eq       	=> 'EQUALS',
	gt       	=> 'GREATER',
	ipMatch  	=> "CIDR_MATCH",
	pm       	=> "PM",
	**pmFromFile 	=> "PM",**
	rx       	=> 'REGEX',
	streq    	=> "EQUALS",
	within   	=> "EXISTS",
};

$operator ||= 'rx';

	if($operator eq "pmFromFile"){
		my $pmFromFileData = $pattern;
		open my $handle, '<', $pmFromFileData;
		chomp(my @lines = <$handle>);
		close $handle;
		$pattern = join("|", @lines);
	}

	my $parsed = {};

I'm going to test with more rules.

cheers!

**Comment by p0pr0ck5** [comment]
Yeah, there are a few different *FromFile things I want to add in. We can probably abstract that out a bit. It's definitely on the horizon :)

**Comment by rm3nchaca** [comment]
Do you mean implement the *FromFile into the rule engine or use the existing pattern match operator?

**Comment by p0pr0ck5** [comment]
We would use existing FreeWAF operators. The translation script would be responsible for reading the contents of the on-disk file and creating the appropriate pattern. We should never do primitive IO reads in lua :) So things like @pmFromFile or @ipMatchFromFile use FreeWAF's PM or CIDR_MATCH operator, and modsec2freewaf.pl is responsible for creating this, just like your suggestion. I just haven't gotten there yet

**Comment by rm3nchaca** [comment]
Nice!! We are in the same way! Let's test more before submit a patch!

Thanks!!

**Comment by p0pr0ck5** [comment]
@rm3nchaca this was done in 5323c1511d6e4219aa9dc142976e56d5df06e791, as this was already on my list of work to do for this script. Thanks for the input here!

**Comment by rm3nchaca** [comment]
Awesome! Thanks!

**Comment by rm3nchaca** [comment]
Hi Robert!
I've run modsec2freewaf.pl against all owasp-crs-ruleset and this are the
only operators/variables that the .pl doesn't support yet.

That's excelent!

operator beginsWith
operator ge
operator lt
operator rbl
operator validateByteRange
variable ARGS_COMBINED_SIZE
variable FILES_COMBINED_SIZE
variable FILES_NAMES
variable f)tps?
variable GEO
variable GLOBAL
variable IP
variable MATCHED_VARS
variable MULTIPART_STRICT_ERROR
variable MULTIPART_UNMATCHED_BOUNDARY
variable REQBODY_ERROR
variable REQUEST_BASENAME
variable REQUEST_BODY
variable REQUEST_PROTOCOL
variable REQUEST_URI_RAW
variable Transfer-Encoding)/'
variable WEBSERVER_ERROR_LOG
variable XML

Cheers!

**Comment by p0pr0ck5** [comment]
Yes, there are still a number of unsupported operators and variables at this point. This branch is still a work in progress :)

There will be some variables and functionality  that we simply cannot support (such as blocking transactions via phase 4 rules; nginx architecture simply will not allow this). I also suspect things like WEBSERVER_ERROR_LOG and validateByteRange won't be of use to us, nor will we have an available translation.

I'm hoping to finish and merge the modsec2freewaf branch into development by the end of this week, and tag a new release with this functionality shortly thereafter :)
