### ISSUE TITLE
mp4 is not in "whitelisting extensions - media"

### ISSUE THREAD

**Issue by emrahcom** [p0pr0ck5/FreeWAF#25]
Hi Robert,

mp4 is not in "whitelisting extensions - media", rule id: 10007

/test.mp3?a=a' union select  --> pass
/test.flv?a=a' union select  --> pass
/test.mp4?a=a' union select  --> forbidden

**Comment by p0pr0ck5** [comment]
Thanks for catching this! I've added it to the pattern on the development branch, and it will get pushed to master with the v0.5 release (should be a few weeks from now).
