### ISSUE TITLE
How to effectively create "whitelist"

### ISSUE THREAD

**Issue by x86fantini** [p0pr0ck5/FreeWAF#305]
Hi, thanks again for this wonderful project!. I'm trying to use is with a couple of Magento, to protect my instalation.

I have ended up disabling the WAF since i was not able to whitelist certain requests.

**whitelist ip**
the URL www.domain.com/backadmin is the door to manage Magento. how can i whitelist this url since it will be accessed only from my office IP 1.2.3.4 ?

**whitelist url**
the URL www.domain.com/checkout should never be filtered by waf. how can i add it to a url whitelist soft of?

**whitelist string**
the URL www.domain.com/cart?abc should never be filtered by waf. how can i add it to a URI whitelist soft of?

it's not ideal to just drop the whole rule since in other part of the website i need that rule

thank you again

thank you very much
S.

**Comment by p0pr0ck5** [comment]
Hi,

There are a few options for your use cases:

- Create a separate `location` block that does not implement the lua-resty-waf logic
- Implement some custom logic in your access handlers that exits Lua handler (or does not execute the `lua-resty-waf:exec` caller) based on the client IP
- Write a custom SecRules rule and integrate it into your existing rulesets

Hopefully this helps! You may want to look at the [ModSecurity reference](https://github.com/SpiderLabs/ModSecurity/wiki) for writing custom SecRules directives to fine-tune your integration.
