### ISSUE TITLE
How can I handle log by myself?

### ISSUE THREAD

**Issue by gavinv587** [p0pr0ck5/FreeWAF#312]
I  found there are some functions about log. However, I want to save the log of waf  by redis. How could I get the content of waf's log?

**Comment by rbustos** [comment]
Not sure if it could be done directly.. but try with filebeats. Install filebeats in your waf machine and send log data to your redis or logstash (ELK recommended)

https://www.elastic.co/guide/en/beats/filebeat/current/redis-output.html

**Comment by p0pr0ck5** [comment]
Hi,

Sorry for the delayed response. Yes, shipping logs elsewhere is supported, either via file or socket (though I discourage the former as it has substantial negative performance implications). Using something like filebeat to ship off on-disk logs is a good solution.
