### ISSUE TITLE
Error in using modsec2lua-resty-waf.pl

### ISSUE THREAD

**Issue by Mark3un** [p0pr0ck5/FreeWAF#318]
Hi: 
    Thanks for your lua-resty-waf:-)

perl modsec2lua-resty-waf.pl -h

_**Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/%{ <-- HERE ([^}]+)}/ at /usr/local/perl/lib/site_perl/5.28.1/Modsec2LRW.pm line _983.**_
Usage modsec2lua-resty-waf.pl < <data> [hqspP]
Translate ModSecurity configs to lua-resty-waf rulesets, reading from standard input and writing to standard output.

  -h|--help      Print this help
  -q|--quiet     Be quite when translating (do not print imcompatible chains)
  -s|--silent    Be silent when translating (do not print any information apart from translated rules)

------------------------------------------------------------------------------------------------------------
Is this the right way to use it?

_**perl modsec2lua-resty-waf.pl -p /home/now/waf_admin/owasp-modsecurity-crs-3.2-dev/rules/REQUEST-901-INITIALIZATION.conf -f**_

-----------------------------------------------------------------------------------------------------------

How to solve the issue?

Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/%{ <-- HERE ([^}]+)}/ at /usr/local/perl/lib/site_perl/5.28.1/Modsec2LRW.pm line 983.

**Comment by Mark3un** [comment]
Wish your answer. Thank you very much.@p0pr0ck5

**Comment by p0pr0ck5** [comment]
Hi,

Yeah, we should probably escape out those braces. That said, i expect eventually this Perl script will go away and this should rely solely on the Lua translation module.
