### ISSUE TITLE
403 forbidden when URI contains "rsa" or "dsa"

### ISSUE THREAD

**Issue by emrahcom** [p0pr0ck5/FreeWAF#32]
Hi Robert,

FreeWAF prevents to access the pages when its uri contains "rsa" or "dsa"

www.mysite.com/xxxrsaxxx/ <- forbidden
www.mysite.com/xxxdsaxxx/ <- forbidden
www.mysite.com/xxxyyyxxx/ <- pass

Rule id: 90002

**Comment by emrahcom** [comment]
This is the current development branch.

**Comment by p0pr0ck5** [comment]
The rule itself has some merit, but the regex needs work. I won't have much time to develop this week, so if the rule is causing problems you should add the following to your config for now:

`set_option("ignore_rule", 90002)`

**Comment by p0pr0ck5** [comment]
Hi,

I've updated the regex for this rule to more precisely match the target pattern (see the rule description for a diary post containing more details); let me know if this is still causing issues for you.

**Comment by p0pr0ck5** [comment]
Closing this so I can push a new release. Let me know if you see any more problems with this.
