### ISSUE TITLE
RESPONSE-95xx.conf doesn't work

### ISSUE THREAD

**Issue by Mark3un** [p0pr0ck5/FreeWAF#321]
Hi：
I find it doesn't work. when I use the RESPONSE rules（RESPONSE-95xx.conf），That would mean I can't filter response body.

Because I didn't load the crs-setup.conf.example configuration? I must load that and config ResponseBodyAccess SecRequestBodyAccess, cache the body first.After that I could use RESPONSE-95xx.conf and filter response body.

How to use RESPONSE-95xx.conf rules？
 
Look forward to your reply  thank you.

**Comment by Mark3un** [comment]
load the 95x.conf rules and config this in nginx.conf：

body_filter_by_lua_block {
                    local lua_resty_waf = require "resty.waf"
                    local waf = lua_resty_waf:new()
                    waf:exec()
                }

**Comment by zffocussss** [comment]
@GumpSun  can you help me how to load the 95x.conf rule set file,which should be imported from coreruleset?

**Comment by Mark3un** [comment]
> @GumpSun can you help me how to load the 95x.conf rule set file,which should be imported from coreruleset?

@zffocussss RESPONSE-95xx.conf rules belong to body phase，you should load that in body_filter_by_lua_block.
