### ISSUE TITLE
which is better performance in  lua_resty_waf.load_secrules or add_ruleset

### ISSUE THREAD

**Issue by redbox-cdn** [p0pr0ck5/FreeWAF#323]
Which is better performance in  lua_resty_waf.load_secrules or add_ruleset? 

My understanding is that
If  case of json, when nginx started load in the memory. 
if crs files, lua resty waf will convert into json and then load in the memory.
is that performance both same?

If there is something to consider, please advice me.

**Comment by Mark3un** [comment]
You could load the crs rules in redis or share_dict of nginx, We must convert into json. And that happen in init phase, Don't worry about this performance,we use the crs rule int access head or body phase,we must focus on matching the crs rules and improve this performance.
