### ISSUE TITLE
Level of logging

### ISSUE THREAD

**Issue by splitice** [p0pr0ck5/FreeWAF#38]
When debugging I have noticed an extreme amount of debug output. I propose reducing some of the mostly superfluous output. I propose starting with utility methods. This has an added benifit of simplifying the signatures for these outling methods.

Some possible targets include the operators.*:
```
_log(self, "Needle is a table, so recursing!")
```

and
````
_log(self, "Comparing (greater) " .. tostring(a) .. " and " .. tostring(b))
```

Some information from this could be included in the log output of process rule instead, possibly grouped with another message.

This has the added benefit of making the utility functions more generic and suitable for use from module context (not just wf context) where logging is not available.

Some work in this area is in my fork.

**Comment by p0pr0ck5** [comment]
Debug statements are most useful when debugging, obviously- those particular statements have been useful in catching mistakes and identifying issues I didn't know where around. Perhaps its time to add some configurable granularity to debug logs?

**Comment by splitice** [comment]
Yes and no, its debug logs so they can be a bit verbose. Personally I just think logging inside utility functions i.e the ```_table_``` functions to be redundant. These functions should instead be rigorously tested. Application specific logging can then occur outside if necessary.

This also allows for these utility functions to be used in the module context where options are unavailable. I found I needed to do this in my branch a few times (e.g ```_table_clone``` on the default options)

**Comment by hy05190134** [comment]
I agree with splitice. Some logging is unnecessary, and I think _log should supply for log level directly, as for the logging content, we should write it before thinking about seriously.

**Comment by p0pr0ck5** [comment]
"Personally I just think logging inside utility functions i.e the _table_ functions to be redundant. These functions should instead be rigorously tested. Application specific logging can then occur outside if necessary."

Yep, the more I look at this, this more I agree. Once I finish breaking out lookup tables and various functions into smaller libraries, we can start unit testing with something like Test::Nginx::Socket::Lua, and the nasty debug logs can go away.

**Comment by p0pr0ck5** [comment]
More work done on this in:

b814a4260fc2f6059f9f11590dbc7981a873446a
feb57634b567d92ff0d474b2ca15c9ed30c49c9c
493391db445de31dbaa2985118ba3ce5afef361a

If there are suggestions on cleaning this further, feel free to submit a PR :)
