### ISSUE TITLE
why not use "transform = xxx" in  var' opts table

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#40]
I suggest you can put "transform = xxx" from rule.opts to rule.var.opts, because var will be token action on transformation before match.

**Comment by p0pr0ck5** [comment]
I didn't want to add yet another value into rule.var.opts; there doesn't seem to be any performance penalty either way. I'm not sure I understand the second portion of your statement.

**Comment by hy05190134** [comment]
I just mean transform function is close to var, so I suggest put into var's opts instead of rule's opts
