### ISSUE TITLE
how to handle many keys

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#41]
request_headers.host =>   opts = { key = "specific", value = "host"}

how to handle request_headers.host and request_headers.user-agent ?

to be opts = {key = "specific", value = {"host", "user-agent"}} ?

**Comment by p0pr0ck5** [comment]
You need to write multiple rules to pick multiple specific values from a collection. Getting multiple specific values is not supported at this time. Patches welcome.

**Comment by hy05190134** [comment]
I have pull request for the patch, If you think it is acceptable, you can merge it. By the way, memokey is one of the optimisations in freewaf, and I want to know whether you have optimisation towards functions like equal, greater, etc, or have they already optimized by luajit?

**Comment by p0pr0ck5** [comment]
There are no optimization of function primitives, that's not our concern. We use memoization to prevent needlessly burning CPU cycles by performing the same string manipulations multiple times.
