### ISSUE TITLE
performance  questions?

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#42]
process transactions in roughly 300-500 microseconds per request; this equals the performance advertised by Cloudflare's WAF.  

But as far as I know, CF's transaction time is 300-500us, less than 1 ms, why equals ?

**Comment by p0pr0ck5** [comment]
"us" is an abbreviation of microseconds, they are the same thing. "ms" is milliseconds, 1000 microseconds. Note that microseconds is actually represented by the Greek character mu ("μ"), but because is this not available in 8-bit ASCII, microseconds are often conveniently represented with "us".
