### ISSUE TITLE
consult for  owasp's core rule

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#47]
Do you know  "t:none,t:urlDecodeUni" mean the variables do operator twice? one for none transform function, another for urlDecodeUni transform function?

and I get to know you are doing the work that translate owasp's core rule to your own rule set, what's your schedule ？

**Comment by p0pr0ck5** [comment]
"Do you know "t:none,t:urlDecodeUni" mean the variables do operator twice? one for none transform function, another for urlDecodeUni transform function?"

Yes, I know this. FreeWAF already provides for this, multiple transforms can be defined by setting the `transform` rule opt as a table. t:none also resets any inherited transforms in ModSecurity; FreeWAF doesn't support a concept of default transforms, so this is a non-issue.

"and I get to know you are doing the work that translate owasp's core rule to your own rule set, what's your schedule ？"

OWASP doesn't have a core rule set- ModSecurity does, which is what the included ruleset is based on.
