### ISSUE TITLE
resty.upload dependency

### ISSUE THREAD

**Issue by emrahcom** [p0pr0ck5/FreeWAF#51]
Hi Robert,

I installed the current master branch to Debian Jessie box with Nginx 1.6.2 from Debian repo.
I get "module 'resty.upload' not found" error message.

Is it possible to put this module under FreeWAF's directory tree like "inc.resty.cookie"? 

regards

**Comment by p0pr0ck5** [comment]
Sure, this shouldn't cause an issue. resty.upload is part of the OpenResty build packages, but I don't see a reason not to include it locally.

**Comment by p0pr0ck5** [comment]
Added in 2e4ac47f3d7c8906f96a5166de4dd0b576b7b767. Let me know if this is working for you.

**Comment by p0pr0ck5** [comment]
Closing after no response and patch provided.
