### ISSUE TITLE
about 42000.lua

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#52]
why 42000.lua 's regex expression use "" in pattern, but others use [=[ ]=].

**Comment by hy05190134** [comment]
you have double 90007 rule, so maybe should modify

**Comment by p0pr0ck5** [comment]
These are two separate issues.

"why 42000.lua 's regex expression use "" in pattern, but others use [=[ ]=]."

I used some Perl code to convert these rules, and the JSON decode resulted in the style difference. There is no performance difference.

"you have double 90007 rule, so maybe should modify"

This is an unrelated issue. New bug please :)
