### ISSUE TITLE
a little bug slash bexpression

### ISSUE THREAD

**Issue by chenyoufu** [p0pr0ck5/FreeWAF#55]
```
{
		id = 42009,
		action = "SCORE",
		description = "XSS (Cross-Site Scripting)",
		opts = { score = 4, transform = { 'html_decode', 'compress_whitespace' } },
		var = {
			operator = "REGEX",
----			pattern = "\\bstyle\\b\\W*\\=.*bexpression\\b\\W*\\(",
++++          pattern = "\\bstyle\\b\\W*\\=.*\\bexpression\\b\\W*\\(",
			type = "REQUEST_ARGS",
			opts = { key = "all" },
		},
	},
```

**Comment by p0pr0ck5** [comment]
This regex was taken directly from the ModSecurity CRS, which the included ruleset attempts to follow:

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/master/base_rules/modsecurity_crs_41_xss_attacks.conf

Feel free to open a bug with them; if it's patched we can update as follows.

**Comment by hy05190134** [comment]
I think  chenyoufu is right and Mod has accepted his suggestion.

**Comment by hy05190134** [comment]
and also, in 40000.lua,  40015 :  REQUST_ARGS ->  REQUEST_ARGS,  simple bug

**Comment by hy05190134** [comment]
and also, 40017: REQUEST_ARGS  wrong

**Comment by hy05190134** [comment]
@p0pr0ck5

**Comment by p0pr0ck5** [comment]
Sorry for the delay, I have been very busy outside of this project. I will have significantly less time to develop this going forward, but I have fixed these for now. Thanks for the report.

**Comment by hy05190134** [comment]
you can add me to be committer, @p0pr0ck5
