### ISSUE TITLE
not match form-data type attack data

### ISSUE THREAD

**Issue by loveshell** [p0pr0ck5/FreeWAF#58]
https://github.com/p0pr0ck5/FreeWAF/blob/development/fw.lua#L550

return nil

then it not match form-data type attack data

**Comment by p0pr0ck5** [comment]
This is not a bug. We do not set the `REQUEST_BODY` collection if a multipart/form-data request was sent; this follows the default behavior of the ModSecurity CRS (except that we do not do strict multipart checking), because form uploads are much more likely to result in false positives.
