### ISSUE TITLE
about ignore key 

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#62]
you have designed ignore key to get rid of some key value, but it desn't include in your rules, but I see mod security has some rules ignore "__utm", so what's your opinion?

**Comment by p0pr0ck5** [comment]
Key ignores could definitely benefit from regex use. Patches welcome :)

**Comment by hy05190134** [comment]
I have offer two patches, please review to accept?

**Comment by hy05190134** [comment]
677     local request_cookies, cookie_err = cookies:get_all()                                                     
 678     -- get rid of __utm & _pk_ref in cookies                                                                  
 679     if request_cookies ~= nil then                                                                            
 680         for k, v in pairs(request_cookies) do                                                                 
 681             if ngx.re.find(k, [=[^__utm]=], self._pcre_flags) then                                            
 682                 request_cookies[k] = nil                                                                      
 683             elseif ngx.re.find(k, [=[^_pk_ref]=], self._pcre_flags) then                                      
 684                 request_cookies[k] = nil                                                                      
 685             end                                                                                               
 686         end                                                                                                   
 687     end                                                                                                       
 688     local request_common_args = _build_common_args(self, { request_uri_args,                                  
 689         request_post_args, request_cookies })

**Comment by p0pr0ck5** [comment]
First, please don't put diffs in comments. It's unreadable and unusable.

Second, no, we would need a generic regex to ignore keys, not just ignore hard-coded specifics.

**Comment by p0pr0ck5** [comment]
Closing this in favor of issue #74.
