### ISSUE TITLE
lua-resty-upload doesn't support spdy protocol

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#64]
lua-resty-upload use ngx.req.socket which is not supported by spdy  protocol. Since the multi-part segment is just for format valid checking ,  so we suggest just to call ngx.req.discard() when deny the request.

**Comment by p0pr0ck5** [comment]
Not really sure what to make of this. If lua-resty-upload doesn't support spdy, shouldn't that be handled by upstream, and not here? And if we deny the request, why do we need to discard()?

**Comment by hy05190134** [comment]
Since the body is not handled to check, we just jump over the phases to avoid the problem.

**Comment by p0pr0ck5** [comment]
I still don't think I understand what you're saying. Can you please clarify (or ask someone to translate)?

**Comment by hy05190134** [comment]
just don't accept the body using lua-resty-upload

**Comment by p0pr0ck5** [comment]
I don't know that I'm a fan of such a fail-open approach, at least by default. We could make this a module option on how to respond to spdy POST multipart/form-data requests. Patches welcome.

**Comment by hy05190134** [comment]
why not accept my other patch

**Comment by p0pr0ck5** [comment]
Closing this. SPDY is on the way out, and the scope of this ticket is lua-resty-upload, not us.
