### ISSUE TITLE
cookie.lua

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#65]
you have add some debug statement like 'print' in cookie.lua?

**Comment by p0pr0ck5** [comment]
No.

**Comment by hy05190134** [comment]
@p0pr0ck5  but you indeed have print in your cookie.la

**Comment by p0pr0ck5** [comment]
Hi, sorry, not sure what happened here, I will push up the latest version of cookie.lua to the development branch. Thanks.
