### ISSUE TITLE
why not use ngx.re.gsub

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#67]
I just find that you use string.gsub in html_decode, so why not use ngx.re.gsub instead of string.gsub as it can improve performance.

**Comment by p0pr0ck5** [comment]
This would likely be helpful, since transformation caching is on by default it likely won't make a big impact, but for consistency's sake we should indeed use this. Patches welcome (I may be able to resume some consistent development some time in the next few months)
