### ISSUE TITLE
html_decode  

### ISSUE THREAD

**Issue by hy05190134** [p0pr0ck5/FreeWAF#68]
towards &#x(%d+) should be &#x(%x+) 
![screen shot 2015-07-28 at 11 58 11 am](https://cloud.githubusercontent.com/assets/7495796/8923236/9a57ee60-3520-11e5-97de-667ec7507ea7.JPEG)

**Comment by p0pr0ck5** [comment]
Non-issue since switching to ngx.re.gsub
