### ISSUE TITLE
Error with non-default allowed_content_types in config

### ISSUE THREAD

**Issue by mickygough** [p0pr0ck5/FreeWAF#79]
Using fw:set_option("allowed_content_types", { "text/html", "text/json", "application/json" } ) in the openresty config was ineffective as _allowed_content_types was not populated on initialisation.

This resulted in errors trying to find needle ("application/json") in haystack ("") because haystack was a string, not a table. Openresty replied with a 500 response code and the following in error.log:

"2015/12/29 13:06:39 [error] 1838#0: *7 lua entry thread aborted: runtime error: /opt/openresty/lualib/FreeWAF/fw.lua:26: Cannot search for a needle when haystack is type string
stack traceback:
coroutine 0:
[C]: in function 'error'
/opt/openresty/lualib/FreeWAF/fw.lua:26: in function '_fatal_fail'
/opt/openresty/lualib/FreeWAF/fw.lua:136: in function '_table_has_value'
/opt/openresty/lualib/FreeWAF/fw.lua:564: in function '_parse_request_body'
/opt/openresty/lualib/FreeWAF/fw.lua:782: in function 'exec'
access_by_lua(matrix-common:93):19: in function , client: ...."

I've sent in a pull request that fixes the issue.

**Comment by p0pr0ck5** [comment]
I'm going to close this as an issue is generated when you create a pull request (see #78).
