### ISSUE TITLE
add_rulesets directive

### ISSUE THREAD

**Issue by mickygough** [p0pr0ck5/FreeWAF#81]
Feature request.

It'd be good to be able to specify an additional ruleset for system-specific use. That way it can be maintained separately to the main repo without breaking updates.

I imagine the configuration line would look something like:

fw:set_option("add_ruleset", "97000")

and the result would be that the file rules/97000.lua would then be included by adding 97000 to self._active_rulesets.

**Comment by mickygough** [comment]
I've got the code for this but don't know how to submit it as a pull request without the previous pull request included :(

I can give you a git diff or throw in a pull request with both?

**Comment by p0pr0ck5** [comment]
May I suggest you use different local branches to make your changes? That way each pulrelated only to changes on that branch.l request.

Also, in the future, please submit pull requests to the development branch of this repo. I have to clean this branch up (I'll probably tag a 0.5.2 release with a few tweaks and your changes) shortly, but for the future I'd like to keep changes off the master branch.

**Comment by mickygough** [comment]
Thanks for the pointers. I'll read up on git and branches and try to be a better citizen in the future. Apologies for polluting the master branch.

**Comment by mickygough** [comment]
Hi p0pr0ck5,

I think I've got the pull requests right this time. Please let me know if I haven't and I'll remove them.

**Comment by mickygough** [comment]
Closing this issue as another was created with the pull request.
